version: '3'

services:
    learning-center:
        build: .
        depends_on:
            - redis-server
        ports:
            - "3001:3000"
        environment: 
            - NODE_PORT=3000
            - REDIS_HOST=redis-server
            - REDIS_PORT=6379


    redis-server:
        image: redis:6.0.9
        volumes: 
            - redis-data:/data

volumes: 
    redis-data:
